---
namespace: odem
name: base
version: 0.3.2
readme: README.md
authors:
  - foo <bar@baz.com>
description: Shared conventions and dependency anchor for the odem.* collection ecosystem
license:
  - GPL-3.0-or-later
tags:
  - odem
  - base
  - conventions
repository: https://github.com/my-perfect-system/odem-base
documentation: https://github.com/my-perfect-system/odem-base
homepage: https://github.com/my-perfect-system/odem-base
issues: https://github.com/my-perfect-system/odem-base/issues
build_ignore:
  - .ansible-lint
  - .yamllint
  - .git
  - .github
  - .gitignore
  - "*.tar.gz"
